1.i.  python library is reusable code(means already written by someone so we can use without writting from scratch just 
        import and use number of times)
   ii.its optimized format exection will take less time 
   

2.list:-can store heterogenous data
  numpy array stores homogenous data and also and we can perform numerical calculation faster than list

3.shape,size fo array

In [46]:
a= [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
import numpy as np
arr=np.array(a)
arr.shape


(3, 4)

In [47]:
#3(ii)
arr.size

12

In [48]:
#3(iii)
arr.ndim

2

4.first row of the following array

In [75]:
arr[0:1]

array([[1, 2, 3, 4]])

5.accesing third row fouth column

In [76]:
arr[[2],[3]]

array([12])

6.all odd-indexed elements 

In [89]:
a_1=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
arr_1=np.array(a_1)
odd=arr_1[0:3,[1,3]]
odd

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7 random 3*3 matrix

In [80]:
import random
a=np.random.randint(0,1,size=(3,3))
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

8. the main difference between both functions is the distribution of the generated random numbers: numpy.random.rand() produces numbers in a uniform distribution [rand] and numpy.random.randn() produces numbers in a normal distribution

9.increase the dimesnion of the array


In [81]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10.transpose the matrix

In [82]:
tran_arr=arr.T
tran_arr

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11.1.index wise multiplication

In [58]:
a=[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]]
b=[[1,2,3,4],
    [5,6,7,8],
       [9,10,11,12]]
mat_a=np.array(a)
mat_b=np.array(b)

In [60]:
mult=mat_a*mat_b
mult

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

ii.matrix multiplication

In [62]:
mat_b_tr=mat_b.T
mat_a@mat_b_tr

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

iii.matrix addition

In [63]:
mat_a+mat_b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

iv.subraction of mat

In [64]:
mat_b-mat_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

v.division matrix


In [65]:
mat_b/mat_a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.
byteswap() method swaps the bytes of the array elements. It toggles between low-endian and big-endian data representation by returning a byteswapped array, optionally swapped in-place

13.calculate the inverse of a matrix.

14.enables you to change the shape of an array into another compatible shape.
np.reshape()

15.how NumPy treats arrays with different shapes during arithmetic operations